services:
  s3server:
    image: scality/s3server:latest
    container_name: mvp_s3server
    restart: unless-stopped
    ports:
      - "8020:8000"
    volumes:
      - s3data:/usr/src/app/localData
      - s3metadata:/usr/src/app/localMetadata
    environment:
      - SCALITY_ACCESS_KEY_ID=newAccessKey
      - SCALITY_SECRET_ACCESS_KEY=newSecretKey
      - SSL="FALSE"